site_name: Adamanteye Note
repo_url: https://github.com/adamanteye/adamanteye.github.io
repo_name: Adamenteye.github.io

nav:
  - 简介: index.md
  - Optics:
    - Fabry-Perot Interferometer: optics/fabry-perot-interferometer.md
    - Coherent Theory: optics/coherent-theory.md
    - Diffraction: optics/diffraction.md
  - 基础物理实验:
    - 绪论: physics-lab/intro.md
  - R语言:
    - 基础语法: r/basics.md
    - ggplot2 绘图包: r/ggplot2.md
  - 德语:
    - 新编大学德语一:
      - Einheit 9: deutsch/klick-auf-deutsch-1/einheit-9.md
      - 语法总结: deutsch/klick-auf-deutsch-1/grammatik.md
      - 不规则动词表: deutsch/klick-auf-deutsch-1/verben.md
  - 写作与沟通:
    - 高效沟通: writing/communication.md
    - 文件综述: writing/literature-review.md
    - 利用图书馆: writing/libarian.md
  - JAVA:
    - 基础语法: java/basics.md
  - 计算机图形学:
    - OpenGL 入门: graphics/opengl-tutorial.md
  - 人文社科:
    - 中国近现代史纲要: social-sci/modern-history.md

theme:
  language: zh
  name: material
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.copy

  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换到夜间模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到日间模式

  icon:
    repo: fontawesome/brands/github

  plugins:
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date-localized:
      enable_creation_date: true
      locale: zh

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition # !!! 格式支持
  - pymdownx.arithmatex: # latex 公式支持
      generic: true
  - pymdownx.highlight:
      linenums: true # 显示代码块行号
  - pymdownx.details # 折叠格式 ???
  - footnotes
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 

  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {percent_encode: True}}