site_name: Adamanteye Note
repo_url: https://github.com/adamanteye/adamanteye.github.io

nav:
  - 简介: index.md

  - 德语:
    - 新编大学德语一:
      - Einheit 9: deutsch/klick-auf-deutsch/einheit-9.md

theme:
  language: zh
  name: material
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  features:
    - navigation.tabs
    # - navigation.instant
    # - navigation.footer
    # - navigation.top
    # - content.action.view

  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: 切换到夜间模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换到日间模式

  icon:
    repo: fontawesome/brands/github

  plugins:
  - search:
      separator: '[\s\u200b\-]'

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition # !!! 格式支持
  - pymdownx.arithmatex: # latex 公式支持
      generic: true
  - pymdownx.highlight:
      linenums: true # 显示代码块行号
  - pymdownx.details # 折叠格式 ???
  - footnotes


  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {percent_encode: True}}